Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder ".", "/vagrant", type: 'virtualbox'

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update -y
     sudo apt-get upgrade -y
     aptitude install -y apache2 vim libapache2-mod-php5 sqlite3 php5 php5-cli php5-curl php5-dev php5-intl php5-mcrypt php5-sqlite
     sudo echo '
<VirtualHost *:80>
    DocumentRoot "/var/www/"
    ServerName example.com
    ServerAlias www.example.com
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>' >  /etc/apache2/sites-available/default.conf
     rm -rf /var/www/
     ln -s /vagrant /var/www
     sudo a2ensite default
     sudo a2dissite 000-default
     sudo rm /etc/apache2/sites-available/000-default.conf
     sudo a2enmod rewrite
     sudo sed -i '166s/None/All/' /etc/apache2/apache2.conf
     sudo service apache2 restart
   SHELL
end
